#!/usr/bin/python
import sys
import subprocess 
import ConfigParser
import getopt 
import queue

options, arguments = getopt.getopt(sys.argv[1:], 'vc:')

# Check if we got at least two (non-option) arguments, queue name and command
if len(arguments) < 2:
    sys.stderr.write("Usage: dequeue [-v] <queue-name> <command> ...\n")
    sys.exit(2)

# System-wide configuration file
config_file = '/etc/queue-cli/queue-cli.conf';

# Reading options (well, just verbose option)
verbose = False
for o, a in options:
    if o == "-v":
        verbose = True
    elif o =="-c":
        config_file = a

# Read configuration files to see if 
from ConfigParser import SafeConfigParser
parser = SafeConfigParser()
parser.read(config_file)

try:
    config_pairs = parser.items(arguments[0])
except ConfigParser.NoSectionError:
    sys.stderr.write("No such queue defined: " + arguments[0] + "\n")
    sys.exit(1)

# Send log messaged to STDERR if -v was passed
def log(log_message):
    if (verbose):
        sys.stderr.write(log_message + "\n")
    
config = {}
for name, value in config_pairs:
    config[name] = value

message = queue.SQS(config).dequeue()

if (message is None):
    log("No messages in the queue")
    sys.exit(0)

command = arguments[1:]

log("Executing: " + " ".join(command) + " passing message into STDIN")

# send textual representation of the message over to STDIN of the process
proc = subprocess.Popen(command, stdin=subprocess.PIPE)
proc.communicate(str(message))
exitcode = proc.returncode

if (exitcode > 0):
    log("Command exit code: " + str(exitcode))
    log("Returning message back to the queue and exiting with same code")
    message.release()
    exit(exitcode)

log("Command executed successfully, deleting message from the queue")
message.delete()
