#!/usr/bin/python
import sys
import subprocess 
import ConfigParser
import getopt
import queue

options, arguments = getopt.getopt(sys.argv[1:], 'vc:')

# Check if we got one (non-option) argument, queue name
if len(arguments) != 1:
    sys.stderr.write("Usage: enqueue [-v] <queue-name> < file\n")
    sys.exit(2)

# System-wide configuration file
config_file = '/etc/queue-cli/queue-cli.conf';

# Reading options (well, just verbose option)
verbose = False
for o, a in options:
    if o == "-v":
        verbose = True
    elif o =="-c":
        config_file = a

queue_instance = queue.get(config_file, arguments[0])
queue_instance.enqueue(sys.stdin.read())
